services:

  postgres:
    image: postgres:16

    container_name: retail-postgres

    environment:
      POSTGRES_USER: retail
      POSTGRES_PASSWORD: retail
      POSTGRES_DB: retail_dw

    ports:
      - "5432:5432"

    volumes:
      - retail_postgres_data:/var/lib/postgresql/data

volumes:
  retail_postgres_data: