services:

  warehouse:

    image: postgres:16

    restart: unless-stopped

    environment:

      POSTGRES_USER:
        ${POSTGRES_USER}

      POSTGRES_PASSWORD:
        ${POSTGRES_PASSWORD}

      POSTGRES_DB:
        ${POSTGRES_DB}

    volumes:

      - retail_postgres_data:/var/lib/postgresql/data

    healthcheck:

      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]

      interval: 10s
      timeout: 5s
      retries: 5


  airflow-db:

    image: postgres:16

    restart: unless-stopped

    environment:

      POSTGRES_USER:
        airflow

      POSTGRES_PASSWORD:
        ${AIRFLOW_DB_PASSWORD}

      POSTGRES_DB:
        airflow

    volumes:

      - airflow_metadata_data:/var/lib/postgresql/data


  airflow-init:

    image:
      ${AIRFLOW_IMAGE}

    depends_on:

      - airflow-db
      - warehouse

    environment:

      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN:
        postgresql+psycopg2://airflow:${AIRFLOW_DB_PASSWORD}@airflow-db:5432/airflow

      AIRFLOW__CORE__EXECUTOR:
        LocalExecutor

      AIRFLOW__CORE__EXECUTION_API_SERVER_URL:
        http://airflow-api-server:8080/execution/

      AIRFLOW__API_AUTH__JWT_SECRET:
        ${AIRFLOW_JWT_SECRET}

      POSTGRES_HOST:
        warehouse

      POSTGRES_PORT:
        "5432"

      POSTGRES_DB:
        ${POSTGRES_DB}

      POSTGRES_USER:
        ${POSTGRES_USER}

      POSTGRES_PASSWORD:
        ${POSTGRES_PASSWORD}

      PYTHONPATH:
        /opt/retail-data-platform

    volumes:

      - .:/opt/retail-data-platform

    command:

      - bash
      - -c
      - airflow db migrate


  airflow-api-server:

    image:
      ${AIRFLOW_IMAGE}

    restart: unless-stopped

    depends_on:

      airflow-init:
        condition: service_completed_successfully

    environment:

      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN:
        postgresql+psycopg2://airflow:${AIRFLOW_DB_PASSWORD}@airflow-db:5432/airflow

      AIRFLOW__CORE__EXECUTOR:
        LocalExecutor

      AIRFLOW__CORE__EXECUTION_API_SERVER_URL:
        http://airflow-api-server:8080/execution/

      AIRFLOW__API_AUTH__JWT_SECRET:
        ${AIRFLOW_JWT_SECRET}

      POSTGRES_HOST:
        warehouse

      POSTGRES_PORT:
        "5432"

      POSTGRES_DB:
        ${POSTGRES_DB}

      POSTGRES_USER:
        ${POSTGRES_USER}

      POSTGRES_PASSWORD:
        ${POSTGRES_PASSWORD}

      PYTHONPATH:
        /opt/retail-data-platform

    ports:

      - "8080:8080"

    volumes:

      - .:/opt/retail-data-platform

    command:
      api-server


  airflow-scheduler:

    image:
      ${AIRFLOW_IMAGE}

    restart: unless-stopped

    depends_on:

      airflow-api-server:
        condition: service_started

    environment:

      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN:
        postgresql+psycopg2://airflow:${AIRFLOW_DB_PASSWORD}@airflow-db:5432/airflow

      AIRFLOW__CORE__EXECUTOR:
        LocalExecutor

      AIRFLOW__CORE__EXECUTION_API_SERVER_URL:
        http://airflow-api-server:8080/execution/

      AIRFLOW__API_AUTH__JWT_SECRET:
        ${AIRFLOW_JWT_SECRET}

      POSTGRES_HOST:
        warehouse

      POSTGRES_PORT:
        "5432"

      POSTGRES_DB:
        ${POSTGRES_DB}

      POSTGRES_USER:
        ${POSTGRES_USER}

      POSTGRES_PASSWORD:
        ${POSTGRES_PASSWORD}

      PYTHONPATH:
        /opt/retail-data-platform

    volumes:

      - .:/opt/retail-data-platform

    command:
      scheduler


  airflow-dag-processor:

    image:
      ${AIRFLOW_IMAGE}

    restart: unless-stopped

    depends_on:

      - airflow-api-server

    environment:

      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN:
        postgresql+psycopg2://airflow:${AIRFLOW_DB_PASSWORD}@airflow-db:5432/airflow

      AIRFLOW__CORE__EXECUTION_API_SERVER_URL:
        http://airflow-api-server:8080/execution/

      AIRFLOW__API_AUTH__JWT_SECRET:
        ${AIRFLOW_JWT_SECRET}

      POSTGRES_HOST:
        warehouse

      POSTGRES_PORT:
        "5432"

      POSTGRES_DB:
        ${POSTGRES_DB}

      POSTGRES_USER:
        ${POSTGRES_USER}

      POSTGRES_PASSWORD:
        ${POSTGRES_PASSWORD}

      PYTHONPATH:
        /opt/retail-data-platform

    volumes:

      - .:/opt/retail-data-platform

    command:
      dag-processor


  airflow-triggerer:

    image:
      ${AIRFLOW_IMAGE}

    restart: unless-stopped

    depends_on:

      - airflow-api-server

    environment:

      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN:
        postgresql+psycopg2://airflow:${AIRFLOW_DB_PASSWORD}@airflow-db:5432/airflow

      AIRFLOW__CORE__EXECUTION_API_SERVER_URL:
        http://airflow-api-server:8080/execution/

      AIRFLOW__API_AUTH__JWT_SECRET:
        ${AIRFLOW_JWT_SECRET}

      PYTHONPATH:
        /opt/retail-data-platform

    volumes:

      - .:/opt/retail-data-platform

    command:
      triggerer


volumes:

  retail_postgres_data:

  airflow_metadata_data: