retail_analytics:

  target: dev

  outputs:

    dev:

      type: postgres

      host: "{{ env_var('POSTGRES_HOST') }}"

      port: 5432

      user: "{{ env_var('POSTGRES_USER') }}"

      password:
        "{{ env_var('POSTGRES_PASSWORD') }}"

      dbname:
        "{{ env_var('POSTGRES_DB') }}"

      schema: silver

      threads: 4