name: CI


on:

  pull_request:

    branches:
      - main

  push:

    branches:
      - main


permissions:

  contents: read


jobs:

  python-tests:

    name: Python Tests

    runs-on: ubuntu-latest


    steps:

      - name: Checkout repository
        uses: actions/checkout@v6


      - name: Set up Python
        uses: actions/setup-python@v5

        with:
          python-version: "3.11"
          cache: "pip"


      - name: Install dependencies

        run: |

          python -m pip install \
            --upgrade pip

          pip install \
            -r requirements.txt


      - name: Compile Python

        run: |

          python -m compileall \
            ingestion \
            scripts \
            product_api


      - name: Run unit tests

        run: |

          pytest -v



  dbt-validation:

    name: dbt Validation

    runs-on: ubuntu-latest


    steps:

      - name: Checkout repository
        uses: actions/checkout@v6


      - name: Set up Python
        uses: actions/setup-python@v5

        with:
          python-version: "3.11"
          cache: "pip"


      - name: Install dependencies

        run: |

          python -m pip install \
            --upgrade pip

          pip install \
            -r requirements.txt


      - name: Validate dbt project

        env:

          POSTGRES_HOST: localhost

          POSTGRES_PORT: "5432"

          POSTGRES_DB: retail_dw

          POSTGRES_USER: retail

          POSTGRES_PASSWORD: retail

        run: |

          dbt parse \
            --project-dir retail_analytics \
            --profiles-dir retail_analytics



  docker-build:

    name: Docker Build

    runs-on: ubuntu-latest


    steps:

      - name: Checkout repository
        uses: actions/checkout@v6


      - name: Build Airflow image

        run: |

          docker build \
            -f Dockerfile.airflow \
            -t retail-airflow:test \
            .